version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: youanduseventplanner
      MYSQL_USER: ahmet
      MYSQL_PASSWORD: SXLV;jFPxT34i%VOYlUX#A6rN^1a;y

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

networks:
  my_network:
    driver: bridge